import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, LegalSection, LegalList } from "@/components/site/LegalPage";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Sakhi" },
      {
        name: "description",
        content:
          "What personal data Sakhi collects, why we collect it, who can see it, how long we keep it and the rights you have over it.",
      },
      { property: "og:title", content: "Privacy Policy — Sakhi" },
      { property: "og:description", content: "How Sakhi collects, uses and protects your personal data." },
    ],
  }),
  component: Privacy,
});

function Privacy() {
  return (
    <LegalPage
      title="Privacy Policy"
      intro="Sakhi handles sensitive information — where you live, when you are alone at home, how you are feeling. We treat it seriously."
    >
      <LegalSection heading="1. What we collect">
        <LegalList
          items={[
            "Account details: full name, email address, phone number, account type.",
            "Profile details: city, avatar image, and for Care Partners a bio, experience, languages and service area.",
            "Booking details: date, time, duration, address, instructions, status and amount.",
            "Verification and training records for Care Partners.",
            "Reviews, complaints and notifications generated by your use of the platform.",
          ]}
        />
      </LegalSection>

      <LegalSection heading="2. Why we collect it">
        <LegalList
          items={[
            "To create and secure your account.",
            "To match you with a Care Partner and deliver the booking.",
            "To verify and train Care Partners so customers stay safe.",
            "To handle complaints, disputes and safety incidents.",
            "To meet legal and tax obligations.",
          ]}
        />
      </LegalSection>

      <LegalSection heading="3. Who can see your data">
        <p>
          Access is enforced at the database level with row-level security policies, not just in the
          app:
        </p>
        <LegalList
          items={[
            "Customers can only see their own profile, bookings and notifications.",
            "Care Partners can only see their own profile, availability, records and bookings assigned to them.",
            "A Care Partner sees a customer's address and instructions only for a booking involving her.",
            "Sakhi administrators can access platform data to run approvals, safety and support.",
          ]}
        />
      </LegalSection>

      <LegalSection heading="4. What we never do">
        <LegalList
          items={[
            "We never sell your personal data.",
            "We never publish your address or phone number publicly.",
            "We never share your health-related notes with anyone other than the Care Partner for that booking.",
          ]}
        />
      </LegalSection>

      <LegalSection heading="5. Security">
        <p>
          Data is stored in a managed PostgreSQL database with encryption in transit, hashed
          credentials handled by our authentication provider, and row-level security on every table
          holding personal data. Secret keys are never exposed to the browser.
        </p>
      </LegalSection>

      <LegalSection heading="6. Retention">
        <p>
          We keep booking and complaint records for as long as needed for safety, accounting and legal
          reasons. Deleting your account removes your profile and cascades to your personal records,
          except where we must retain limited information by law.
        </p>
      </LegalSection>

      <LegalSection heading="7. Your rights">
        <LegalList
          items={[
            "Access and correct your profile at any time from your dashboard.",
            "Request a copy of your data.",
            "Request deletion of your account.",
            "Object to specific processing, where the law allows.",
          ]}
        />
      </LegalSection>

      <LegalSection heading="8. Contact">
        <p>For any privacy question, reach the Sakhi team through the support contact in your dashboard.</p>
      </LegalSection>
    </LegalPage>
  );
}
