/**
 * Single Supabase entry point for the app.
 *
 * The client itself is generated by the platform in
 * `src/integrations/supabase/client.ts` (URL + publishable key come from env).
 * Everything in the app imports from here so there is exactly one client
 * instance and one place to change.
 *
 * NEVER import or expose a service_role / secret key in this file.
 */
export { supabase } from "@/integrations/supabase/client";
export type { Database } from "@/integrations/supabase/types";
